# Generated by Django 4.2.2 on 2023-06-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.post_blog'),
            preserve_default=False,
        ),
    ]
