# Generated by Django 4.2.2 on 2023-06-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_like_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_blog',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
